### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by benohara**
Allow override of colorscheme with g:dotvim_colorscheme

### CODE REVIEW

**Comment by chairfield** [comment]
Any thoughts on when you'll merge this into `dotvim:master`? I'd love to see this change merged through to `dotphiles:master`.

**Comment by benohara** [comment]
They you go, forgot about that!

**Comment by chairfield** [comment]
Thanks!

**Comment by omero** [comment]
:+1: Just i needed Thanks !!

**Pull request merged**
